package catchTry;

public class ExceptionDemo {

	public static void main(String[] args) {
		int a=10;
		int b=0;
		int c=a/b;
		System.out.println("The value of c is   " + c);
		System.out.println("End of Program");
	}

}
